-- !preview conn=channel

SELECT
    TO_CHAR(HAUL_JOIN) AS HAUL_JOIN,
    TO_CHAR(PORT_JOIN) AS PORT_JOIN,
    SAMPLING_STRATA,
    SAMPLING_STRATA_NAME,
    SAMPLING_STRATA_DEPLOYMENT_CATEGORY,
    SAMPLING_STRATA_SELECTION_RATE
FROM
    norpac.debriefed_length_mv
