---
title: "Compare with and without expansion"
author: "Brett Stacy"
date: "2024-08-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# What impact does expanding have on ISS?



# Data



```{r}
out1 = readRDS("C:/Users/bstacy2/OneDrive - UW/UW Postdoc/GitHub Repos/baseISS_data/outputs/ISS_1000iters_output_8_2_24.RDS")

out2 = readRDS("C:/Users/bstacy2/OneDrive - UW/UW Postdoc/GitHub Repos/baseISS_data/outputs/ISS_10iters_output_2024-08-05.RDS")

```




## Compare

```{r, fig.height=4}
# par(mfrow = c(4,1), mar = c(0,0,0,0), oma = c(2, 4, 2, .5), mgp = c(2, .6, 0))
par(mfrow = c(1,1), mar = c(1.5, 3.1, 0, .5), mgp = c(2, .6, 0))

plot(out1$iss_length$YEAR, out1$iss_length$iss, type = "l", ylab = "ISS", xlab = "year", cex.lab = 1.3, ylim = c(0, max(out2$iss_length$iss)*1.1)) 
lines(out2$iss_length$YEAR, out2$iss_length$iss, col = "blue")
legend("topleft", lty = c(1,1), col = c("black", "blue"), legend = c("with expansion", "without expansion"))

```





