---
title: "Plot ISS Using Full Data Set"
author: "Brett Stacy"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidytable)
```



# First time plotting using full data set



# Data



```{r}
out1 = readRDS("C:/Users/bstacy2/OneDrive - UW/UW Postdoc/GitHub Repos/baseISS_data/outputs/ISS_300iters_output_2024-08-08.RDS")

out2 = readRDS("C:/Users/bstacy2/OneDrive - UW/UW Postdoc/GitHub Repos/baseISS_data/outputs/ISS_300iters_output_2024-08-09.RDS")
```


## ISS

```{r, fig.height=4}
# par(mfrow = c(4,1), mar = c(0,0,0,0), oma = c(2, 4, 2, .5), mgp = c(2, .6, 0))
par(mfrow = c(1,1), mar = c(1.5, 3.1, 0, .5), mgp = c(2, .6, 0))

plot(out1$iss_length$YEAR, out1$iss_length$iss, type = "l", ylab = "ISS", xlab = "year", cex.lab = 1.3) 
legend("topright", lty = c(1), col = c("black"), legend = c("with expansion"))


```



## Compare to nss

```{r, fig.height=4}
# par(mfrow = c(4,1), mar = c(0,0,0,0), oma = c(2, 4, 2, .5), mgp = c(2, .6, 0))
par(mfrow = c(1,1), mar = c(1.5, 3.1, 0, .5), mgp = c(2, .6, 0))

plot(out1$iss_length$YEAR, out1$iss_length$iss, type = "l", ylab = "Sample Size", xlab = "year", cex.lab = 1.3, ylim = c(0, max(out1$iss_length$nss)*1.1)) 
lines(out1$iss_length$YEAR, out1$iss_length$nss, col = "orange")
legend("topright", lty = c(1,1), col = c("orange", "black"), legend = c("nominal", "with expansion"))


```






## Compare to ISS from before

```{r, fig.height=4}
# par(mfrow = c(4,1), mar = c(0,0,0,0), oma = c(2, 4, 2, .5), mgp = c(2, .6, 0))
par(mfrow = c(1,1), mar = c(1.5, 3.1, 0, .5), mgp = c(2, .6, 0))

plot(out1$iss_length$YEAR, out1$iss_length$iss, type = "l", ylab = "ISS", xlab = "year", cex.lab = 1.3, ylim = c(0, max(out1$iss_length$iss)*1.3), col = "blue") 
lines(out2$iss_length$YEAR, out2$iss_length$iss, col = "black")
legend("topleft", lty = c(1,1), col = c("black", "blue"), legend = c("onboard domestic only", "after including port & foreign"))


```




## Compare to ISS from 2023 assessment

```{r, fig.height=4}
assessment_2023_iss = tidytable(year = 1977:2023,
                                iss = c(27,
                                45,
                                54,
                                54,
                                63,
                                31,
                                117,
                                140,
                                211,
                                216,
                                396,
                                401,
                                185,
                                189,
                                1565,
                                1543,
                                913,
                                1435,
                                1561,
                                2020,
                                2142,
                                2046,
                                2722,
                                2960,
                                3140,
                                3446,
                                4301,
                                3608,
                                3455,
                                2694,
                                2115,
                                2502,
                                2218,
                                1975,
                                2596,
                                2776,
                                3293,
                                3604,
                                3324,
                                2821,
                                2469,
                                1899,
                                1367,
                                1048,
                                859,
                                1160,
                                706))

par(mfrow = c(1,1), mar = c(1.5, 3.1, 0, .5), mgp = c(2, .6, 0))

plot(out1$iss_length$YEAR, out1$iss_length$iss, type = "l", ylab = "ISS", xlab = "year", cex.lab = 1.3, ylim = c(0, max(out1$iss_length$iss)*1.1), col = "blue") 
lines(assessment_2023_iss$year, assessment_2023_iss$iss, col = "black")
legend("topleft", lty = c(1,1), col = c("black", "blue"), legend = c("2023 assessment", "baseISS"))


```














